// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwwwndatkitpudsgrftu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3d3duZGF0a2l0cHVkc2dyZnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjMxOTcsImV4cCI6MjA1NzE5OTE5N30.byBIitQDY0Njyyz4rmsvyte2E4xtZq2fldjjWRMBRPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);